import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { RobotMissionMasterGeneratedModule, RobotMissionMasterGeneratedSharedModule } from './generated/module.js';
import { RobotMissionMasterValidator, registerValidationChecks } from './robot-mission-master-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type RobotMissionMasterAddedServices = {
    validation: {
        RobotMissionMasterValidator: RobotMissionMasterValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type RobotMissionMasterServices = LangiumServices & RobotMissionMasterAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const RobotMissionMasterModule: Module<RobotMissionMasterServices, PartialLangiumServices & RobotMissionMasterAddedServices> = {
    validation: {
        RobotMissionMasterValidator: () => new RobotMissionMasterValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createRobotMissionMasterServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    RobotMissionMaster: RobotMissionMasterServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        RobotMissionMasterGeneratedSharedModule
    );
    const RobotMissionMaster = inject(
        createDefaultModule({ shared }),
        RobotMissionMasterGeneratedModule,
        RobotMissionMasterModule
    );
    shared.ServiceRegistry.register(RobotMissionMaster);
    registerValidationChecks(RobotMissionMaster);
    return { shared, RobotMissionMaster };
}
